### ISSUE TITLE
Make sure no demo misuses external APIs

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/stackablectl#170]
We need to make sure that we are good netizens and every external API we call should be called with a really low rate limit.

**Comment by sbernauer** [comment]
This will be fixed/improved to approx 0.77 request/s (fetch the 700 stations every 15 mins) for the lakehouse demo in https://github.com/stackabletech/stackablectl/pull/175
The only other demo that needs to be modified is `nifi-kafka-druid-water-level-data`, which should be rather easy (copy/paste)

**Comment by lfrancke** [comment]
Has this been done for both demos? I see #175 is merged.
Has the `nifi-kafka-druid-water-level-data` demo been fixed as well @snocke @sbernauer ?

**Comment by lfrancke** [comment]
Isn't that something @snocke can also do?

**Comment by sbernauer** [comment]
Last part: https://github.com/stackabletech/stackablectl/pull/188
