### ISSUE TITLE
Install the Release part into its own "stackable-operators" namespace

### ISSUE THREAD

**Issue by maltesander** [stackabletech/stackablectl#177]
Currently, we install Demos or Stacks mostly into the default namespace.

This is messy, as cleanup can be hard afterwards without throwing the cluster away.

Installing multiple Demos in different namespaces (as is currently possible), should not be the case either since the same operators are deployed multiple times.

We should offer a switch to install operators, stacks and demos in their own namespaces.

**Comment by Techassi** [comment]
Tracked by #259, fixed by https://github.com/stackabletech/stackable-cockpit/pull/79
