### ISSUE TITLE
Adjust README to be in line with other READMEs

### ISSUE THREAD

**Issue by Techassi** [stackabletech/stackablectl#210]
Include our common README header which can be found across most of our repositories.

**Comment by lfrancke** [comment]
Thank you!

I want it to include links to discord, discussions, our general docs site our homepage 
Basically this bit from our operator readmes:
![image](https://github.com/stackabletech/stackable-cockpit/assets/122850/f61775fd-2ca1-4a5b-b54a-0ab6707414f2)
