### ISSUE TITLE
Check cluster size to check if stack/demos fits on k8s cluster

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/stackablectl#240]
During installation of a stack or demo stackablectl should sum up the available resources (cpu + ram) of the k8s nodes.
Each stack and demo must provide the resource requirements - if not specified we e.g. default to 4 cores and 8 gb ram.
If the resources are not available a warning should be shown. (Alternative solution could be to error out and add a flag to force the installation)

**Comment by Techassi** [comment]
Added in https://github.com/stackabletech/stackable-cockpit/pull/94
