### ISSUE TITLE
Support installing `latest` release

### ISSUE THREAD

**Issue by fhennig** [stackabletech/stackablectl#241]
Support `stackablectl release install latest` to install the latest stable release.
It does not need to show up when executing `stackablectl release list`.
In case latest is specified stackablectl will
1. Get the list of releases as usual
2. Filter to all releases matching `[0-9][0-9]\.[0-9][0-9]?`
3. ~Use semver to sort them descending~ => Not semver compatible, sort them with some custom mechanism
4. Pick the first after sorting

**Comment by lfrancke** [comment]
I'll put this on the board now but for refinement only, I'll make a go/no-go decision afterwards. 
I'd like to understand how easy this is to implement first.

**Comment by sbernauer** [comment]
My estimate would be < 1h in stackablectl. Take list of releases, sort them using semver (?) and use the latest and greatest

**Comment by lfrancke** [comment]
I'll move it forward. Please ping me if it ends up taking more than one day.
