### ISSUE TITLE
stackablectl demo install slow if the working directory contains many subdirectories

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/stackablectl#242]
When installing a demo stackablectl traverses the directory tree under the current working directory. If there are a lot of directories this can take a long time and the demo installation hangs. On the same system running the demo install command in an empty directory allows the job to complete very quickly by comparison.

I've attached a copy of the stackablectl output run with strace. The last console output of the script before it hangs is: 
`[DEBUG] built glob set; 0 literals, 0 basenames, 0 extensions, 0 prefixes, 0 suffixes, 1 required extensions, 0 regexes`

After that you can see that the subdirectories of the working directory are recursivley enumerated.

[stackablectl_strace.txt](https://github.com/stackabletech/stackablectl/files/11063864/stackablectl_strace.txt)

**Comment by lfrancke** [comment]
I wonder why it needs to traverse directories at all...

**Comment by fhennig** [comment]
looks like this is fixed in the new version, I'm closing this.

If you disagree,please reopen @Jimvin
