### ISSUE TITLE
Change default namespaces + Support skipping release installation

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/stackablectl#259]
**The idea is to not implement this in the current version of stackablectl, but instead wait for the remake. This issue only tracks the requirements**

As discussed on-site on 2023-05-09 we want
* A flag to skip installing the release when installing a stack or demo
  * Print a warning, that users are responsible to install operators *in the correct version*
* You can configure the namespace to deploy operators into
  * We default to `stackable-operators`
* You can configure the namespace to deploy the stack + demo into
  * We default to `stackable`
* stackablectl tries to create specified namespaces if not existing
  * If this fails because of missing permissions an error is thrown as the user is suggested to specify operators and demo namespace manually
* Demos have the possibility to say "i can only run in stackable-demo" namespace (in stacks.yaml or demo.yaml). If they do so, a warning is printed when they are installed in a different namespace, saying the demo will likely not work. This can be the case as we have to use FQDN service names so that the TLS certs are valid

**Comment by razvan** [comment]
Looks good to me except that it's not clear how the namespace is specified. I hope that releases will use the existing `--namespace` command line argument. For demos a new config field probably. Correct ?

**Comment by Techassi** [comment]
We currently consider `--operator-namespace` and `--demo-namespace`.
