### ISSUE TITLE
Document the resource requirements for stacks/demos

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/stackablectl#268]
The stacks used for demos specify certain CPU and RAM requirements for each container, it would be useful to have then sum of these appear in the demo documentation to guide users as to the resources required to run them.

In addition to the resources requested by the Stackable components, we also need to account for resources required by non-stackable components (databases and such). The best way to do it would be to install the demos and note all the resources that get used.

resources include: disk space, RAM, CPU

## Step 1: Gather the numbers of demos

- [x] [airflow-scheduled-job](https://docs.stackable.tech/stackablectl/stable/demos/airflow-scheduled-job)
    - CPU: 2401 - 4500
    - RAM: 9010 - 8854 Mi
    - 24GB (8GB Postgres, 2x 8GB Redis)
- [x] [data-lakehouse-iceberg-trino-spark](https://docs.stackable.tech/stackablectl/stable/demos/data-lakehouse-iceberg-trino-spark): already has requirements: 80 cores, 200GB RAM, 1TB PVCs
- [x] [hbase-hdfs-cycling-data](https://docs.stackable.tech/stackablectl/stable/demos/hbase-hdfs-load-cycling-data)
    - CPU: 3000 - 4400
    - RAM: 5638 - 5738 Mi
    - 16GB (3x5GB HDFS, 1GB ZK)
- [x] [jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data](https://docs.stackable.tech/stackablectl/stable/demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data)
    - CPU: 3350 - 5800
    - RAM: 7174 - 7274 Mi
    - 22GB
- [x] [logging](https://docs.stackable.tech/stackablectl/stable/demos/logging)
    - CPU: 6500 - 5200
    - RAM: 5098 - 4895 Mi
    - 27GB
- [x] [nifi-kafka-druid-earthquake-data](https://docs.stackable.tech/stackablectl/stable/demos/nifi-kafka-druid-earthquake-data)
    - CPU: 8700 - 17900
    - RAM: 27746 - 25286 Mi
    - 75GB (kafka log dir 30GB)
- [x] [nifi-kafka-druid-water-level-data](https://docs.stackable.tech/stackablectl/stable/demos/nifi-kafka-druid-water-level-data)
    - CPU: 8900 - 18500
    - RAM: 28042 - 25582 Mi
    - 75GB RAM
- [x] [spark-k8s-anomaly-detection-taxi-data](https://docs.stackable.tech/stackablectl/stable/demos/spark-k8s-anomaly-detection-taxi-data)
    - CPU: 6400 - 8600
    - RAM: 12622 - 9906 Mi
    - 35GB
- [x] [trino-iceberg](https://docs.stackable.tech/stackablectl/stable/demos/trino-iceberg)
    - CPU: 8550 - 12000
    - RAM: 26662 - 22410 Mi
    - 110GB (2x 50GB Minio)
- [x] [trino-taxi-data](https://docs.stackable.tech/stackablectl/stable/demos/trino-taxi-data)
    - CPU: 6800 - 11500
    - RAM: 15822 - 13362 Mi
    - 28GB

## Step 2: Gather the numbers of stacks

- monitoring
    - CPU: 1750
    - RAM: 1714 Mi
    - 110GB
- logging
    - CPU: 5150
    - RAM: 3147 Mi
    - 24GB
- airflow
    - CPU: 3400
    - RAM: 9010 Mi
    - 24GB
- data-lakehouse-airflow-trino-spark
    - 71 cores, 160GB RAM, 1TB pvcs
- hdfs-hbase
    - CPU: 4200
    - RAM: 10758 Mi
    - 21GB
- nifi-kafka-druid-superset-s3
    - CPU: 8900
    - RAM: 28042 Mi
    - 75GB
- spark-trino-superset-s3
    - CPU: 7100
    - RAM: 15910 Mi
    - 36GB
- trino-superset-s3
    - CPU: 6800
    - RAM: 15822 Mi
    - 28GB
- trino-iceberg
    - CPU: 8550
    - RAM: 26662 Mi
    - 110GB
- jupyterhub-pyspark-hdfs
    - CPU: 3350
    - RAM: 7174 Mi
    - 22GB
- dual-hive-hdfs-s3
    - CPU: 7750
    - RAM: 19974
    - 44GB
- tutorial-openldap & openldap
    - CPU: 1950
    - RAM: 2182
    - no pvcs

## Step 3: Put the numbers in the docs

https://github.com/stackabletech/stackablectl/pull/280

**Comment by Techassi** [comment]
I can take a stab at this!
