### ISSUE TITLE
Wrong install instructions in Mac OS Dokumentation

### ISSUE THREAD

**Issue by alexortner** [stackabletech/stackablectl#342]
### Affected version

Latest online documentation

### Current and expected behavior

In the Dokumentation https://docs.stackable.tech/management/stable/stackablectl/installation/  the command for the installation on mac OS ius wrong. 
The command 
``` 
sudo install -m 755 -t /usr/local/bin stackablectl
```
fails with the error that it contains an illegal option -t. 

### Possible solution

It should be instead (for the default zsh terminal)
```
sudo install -m 755 stackablectl /usr/local/bin 
```
Please update the documentation accordingly

### Would you like to work on fixing this bug?

maybe

**Comment by Maleware** [comment]
Hey @alexortner thanks for reporting.

Fixed with: https://github.com/stackabletech/stackable-cockpit/pull/343
