### ISSUE TITLE
stackablectl has hard coded temporary file paths, which cause concurrent operation to fail

### ISSUE THREAD

**Issue by pipern** [stackabletech/stackablectl#39]
I ran stackablectl as one user, and then later as another user, and found that it leaves (maybe only when overall the operation failed) files in `/tmp`, which then causes subsequent invocations of stackablectl to fail if the owner of these files/folders is different: 
```
panic: open /tmp/.helmcache/stackable-stable-index.yaml: permission denied
```
```
panic: open /tmp/.helmrepo: permission denied
```

Might it be that stackablectl can instead use unique filenames for these temporary files?

**Comment by lfrancke** [comment]
We are going to close this issue for now as we've migrated to https://github.com/stackabletech/stackable-cockpit/

If this is still an issue please feel free to open a new issue over there.
