### ISSUE TITLE
Update the quickstart guide with the newest versions

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/stackablectl#62]
The [quickstart guide](https://docs.stackable.tech/stackablectl/stable/quickstart.html) should be updated with the newest versions. It is especially important that stable releases are shown instead of only alpha releases. This would give a more mature impression of the documentation and the tool.

**Comment by sbernauer** [comment]
https://github.com/stackabletech/stackablectl/pull/36 will rework the docs and remove the mentioned outdated sections
https://github.com/stackabletech/stackablectl/pull/55 will implement the demos and the quickstart will use the demos command

**Comment by fhennig** [comment]
done: https://docs.stackable.tech/management/stable/stackablectl/quickstart
