### ISSUE TITLE
Extend README/Documentation

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/stackablectl#85]
- More details about features, link to Homepage etc. (similar to other operators)
- System requirements (or at least "Tested on")
- Build instructions (installing the go toolchain, maybe other stuff?)
- Remove TODOs from README

**Comment by fhennig** [comment]
this repo is going to be archived soon, an is superseded by the https://github.com/stackabletech/demos repo and the https://github.com/stackabletech/stackable-cockpit repo. The demo repo has a nice-ish README and the cockpit README could maybe use some work. Maybe this ticket should be moved/closed/replaced?

**Comment by lfrancke** [comment]
Yep, I'm fine with that.
